-- Cambia el password a el usuario
-- En la siguiente sesión el usuario deberá cambiar el password.

use master;		-- utiliza la base de datos del sistema para verificar el login

IF NOT EXISTS(SELECT * from sys.syslogins WHERE name='MARCAJE')
BEGIN
	CREATE LOGIN MARCAJE		-- si no existe el usuario, crea el login del usuario nuevo
		WITH PASSWORD = '12345' MUST_CHANGE,
		CHECK_EXPIRATION = ON,
		DEFAULT_LANGUAGE = ENGLISH,
		DEFAULT_DATABASE = BIOMETRICOBD;
END
GO

ALTER LOGIN MARCAJE WITH PASSWORD = '12345' 
	MUST_CHANGE UNLOCK,
	DEFAULT_DATABASE = BIOMETRICOBD;
	          
use BIOMETRICOBD;
ALTER USER MARCAJE   
     WITH LOGIN = MARCAJE;

USE BIOMETRICOBD;
GRANT	BACKUP DATABASE,
		BACKUP LOG,
		CREATE DEFAULT,
		CREATE FUNCTION,
		CREATE PROCEDURE,
		CREATE RULE,
		CREATE ROLE,
		CREATE SCHEMA,
		CREATE TABLE,
		CREATE VIEW,
	    CREATE SYNONYM,
		SELECT,
		UPDATE,
		DELETE TO MARCAJE WITH GRANT OPTION;
GO

ALTER ROLE db_owner ADD MEMBER MARCAJE;

--GRANT	SELECT, INSERT, DELETE, UPDATE, ALTER ON SCHEMA :: dbo TO COPEREX;

GRANT	ALTER ANY USER TO MARCAJE;
GO

use master;
GRANT	ALTER ANY LOGIN TO MARCAJE;
GO