use BIOMETRICOBD;

GO
CREATE SCHEMA ESQUEMA_SEGURIDAD AUTHORIZATION MARCAJE;
GO
CREATE SCHEMA ESQUEMA_BIOMETRICO  AUTHORIZATION MARCAJE;
GO
CREATE SCHEMA ESQUEMA_ADMINISTRACION  AUTHORIZATION MARCAJE;
GO
CREATE SCHEMA ESQUEMA_RH  AUTHORIZATION MARCAJE;

