USE BIOMETRICOBD
GO

INSERT INTO [ESQUEMA_SEGURIDAD].[USUARIOS_BIOMETRICO]
     VALUES
           ('MARCAJE', 175, '', 1 ,NULL,'SI')

INSERT INTO [ESQUEMA_SEGURIDAD].[MENU_BIOMETRICO]
     VALUES (1, 'Administración' , 1, 1, 'SI')

INSERT INTO [ESQUEMA_SEGURIDAD].[MENU_BIOMETRICO]
     VALUES (2, 'Modelos del Reloj' , 1, 1, 'SI')

INSERT INTO [ESQUEMA_SEGURIDAD].[MENU_BIOMETRICO]
     VALUES (3, 'Descarga de Marcajes' , 1, 1, 'SI')

INSERT INTO [ESQUEMA_SEGURIDAD].[MENU_BIOMETRICO]
     VALUES (4, 'Reportes' , 1, 1, 'SI')

INSERT INTO [ESQUEMA_SEGURIDAD].[MENU_BIOMETRICO]
     VALUES (5, 'Permisos y Seguridad' , 1, 1, 'SI')

INSERT INTO [ESQUEMA_SEGURIDAD].[MENU_BIOMETRICO]
     VALUES (6, 'Parametros del Sistema' , 1, 1, 'SI')


INSERT INTO [ESQUEMA_SEGURIDAD].[USUARIOS_MENU_BIOMETRICO]
     VALUES
           ('MARCAJE',1,'SI', 'SI', 'SI','SI','SI','SI')


INSERT INTO [ESQUEMA_SEGURIDAD].[USUARIOS_MENU_BIOMETRICO]
     VALUES
           ('MARCAJE',2,'SI', 'SI', 'SI','SI','SI','SI')

INSERT INTO [ESQUEMA_SEGURIDAD].[USUARIOS_MENU_BIOMETRICO]
     VALUES
           ('MARCAJE',3,'SI', 'SI', 'SI','SI','SI','SI')

INSERT INTO [ESQUEMA_SEGURIDAD].[USUARIOS_MENU_BIOMETRICO]
     VALUES
           ('MARCAJE',4,'SI', 'SI', 'SI','SI','SI','SI')

INSERT INTO [ESQUEMA_SEGURIDAD].[USUARIOS_MENU_BIOMETRICO]
     VALUES
           ('MARCAJE',5,'SI', 'SI', 'SI','SI','SI','SI')

INSERT INTO [ESQUEMA_SEGURIDAD].[USUARIOS_MENU_BIOMETRICO]
     VALUES
           ('MARCAJE',6,'SI', 'SI', 'SI','SI','SI','SI')



INSERT INTO [ESQUEMA_BIOMETRICO].[MODELOS_DEL_BIOMETRICO]
     VALUES
           (1, 'ZKTEC', GETDATE(), 'MARCAJE')


INSERT INTO [ESQUEMA_BIOMETRICO].[RELOJES_DE_MARCAJE]
     VALUES
           (1,'Administración','192.168.0.54', 'SI', 1, GETDATE(), 'MARCAJE')

INSERT INTO [ESQUEMA_BIOMETRICO].[RELOJES_DE_MARCAJE]
     VALUES
           (2,'Técnico','192.168.0.55', 'SI', 1, GETDATE(), 'MARCAJE')


--INSERT INTO [ESQUEMA_BIOMETRICO].[DESCARGA_DE_MARCAJES]
--    SELECT [CODIGO_DE_RELOJ]
--           ,[CODIGO_DE_MARCAJE]
--           ,[FECHA_DE_MARCAJE]
--           ,[HORA_DE_MARCAJE]
--           ,[FECHA_GRABACION]
--           ,[CODIGO_DE_USUARIO]
--	FROM PRUEBA_DESCARGA_BIOMETRICO
GO

