USE BIOMETRICOBD
GO


CREATE VIEW [dbo].[VBIO_MARCAJES_EMPLEADOS] AS
SELECT a.CODIGO_DE_MARCAJE,
       a.FECHA_DE_MARCAJE,
       a.HORA_DE_MARCAJE,
       a.CODIGO_DE_RELOJ,
	   b.CODIGO_DE_PERSONAL,
       b.NOMBRE_DEL_PERSONAL,
	   b.CODIGO_UNIDAD_TRABAJO,
	   b.PERSONAL_ACTIVO,
	   c.LUGAR_DE_TRABAJO
  FROM DESCARGA_DE_MARCAJES AS a, PERSONAL AS b,
  UNIDADES_DE_TRABAJO AS c
  WHERE a.CODIGO_DE_MARCAJE   = b.CODIGO_MARCAJE_RELOJ
  AND c.CODIGO_UNIDAD_TRABAJO = b.CODIGO_UNIDAD_TRABAJO
GO



go

CREATE VIEW [dbo].[VBIO_MARCAJES_ORDEN_COLUMNAS] AS

SELECT CODIGO_DE_MARCAJE, 
       FECHA_DE_MARCAJE, 
	   MARCA1, 
	   MARCA2, 
	   MARCA3, 
	   MARCA4, 
	   MARCA5, 
	   MARCA6, 
	   MARCA7, 
	   MARCA8, 
	   MARCA9, 
	   MARCA10,
	   MARCA11,
	   MARCA12
FROM
(
	SELECT FECHA_DE_MARCAJE, HORA_DE_MARCAJE, CODIGO_DE_MARCAJE, 
	'MARCA' + CAST(ROW_NUMBER() OVER (PARTITION BY CODIGO_DE_MARCAJE, 
												   DAY(FECHA_DE_MARCAJE), 
												   MONTH(FECHA_DE_MARCAJE), 
												   YEAR(FECHA_DE_MARCAJE)  
									  ORDER BY HORA_DE_MARCAJE, FECHA_DE_MARCAJE, CODIGO_DE_MARCAJE) AS VARCHAR(10)) AS CANTIDAD_COLUMNAS
	FROM DESCARGA_DE_MARCAJES
	) TEMP
	PIVOT
(
MAX(HORA_DE_MARCAJE)
 FOR CANTIDAD_COLUMNAS IN (MARCA1, MARCA2, MARCA3, MARCA4, MARCA5, MARCA6, MARCA7, MARCA8, MARCA9, MARCA10, MARCA11, MARCA12)
) PIV
GO





GO
CREATE VIEW [dbo].[VBIO_PERFIL_PERSONAL] AS
SELECT a.CODIGO_DE_PERSONAL,
       a.NOMBRE_DEL_PERSONAL,
	   a.CODIGO_UNIDAD_TRABAJO,
	   a.CODIGO_TIPO_PERSONAL,
	   a.ROL_PERSONAL,
	   a.PERSONAL_ACTIVO,
	   a.CODIGO_MARCAJE_RELOJ,
	   b.LUGAR_DE_TRABAJO
  FROM PERSONAL AS a, UNIDADES_DE_TRABAJO AS b
  WHERE b.CODIGO_UNIDAD_TRABAJO = a.CODIGO_UNIDAD_TRABAJO
  AND (a.CODIGO_MARCAJE_RELOJ IS NOT NULL
  OR a.CODIGO_MARCAJE_RELOJ > 0)


GO


GO

CREATE VIEW [dbo].[VBIO_REPORTE_DE_MARCAJES_EMPLEADOS] AS
SELECT a.CODIGO_DE_MARCAJE,
       CONVERT(DATE,a.FECHA_DE_MARCAJE, 105) AS FECHA_DE_MARCAJE, 
	   CONVERT(VARCHAR, a.MARCA1, 8) AS MARCA1, 
	   CONVERT(VARCHAR, a.MARCA2, 8) AS MARCA2, 
	   CONVERT(VARCHAR, a.MARCA3, 8) AS MARCA3, 
	   CONVERT(VARCHAR, a.MARCA4, 8) AS MARCA4, 
	   CONVERT(VARCHAR, a.MARCA5, 8) AS MARCA5, 
	   CONVERT(VARCHAR, a.MARCA6, 8) AS MARCA6, 
	   CONVERT(VARCHAR, a.MARCA7, 8) AS MARCA7, 
	   CONVERT(VARCHAR, a.MARCA8, 8) AS MARCA8, 
	   CONVERT(VARCHAR, a.MARCA9, 8) AS MARCA9, 
	   CONVERT(VARCHAR, a.MARCA10, 8) AS MARCA10, 
	   b.CODIGO_DE_PERSONAL,
       b.NOMBRE_DEL_PERSONAL,
	   b.CODIGO_UNIDAD_TRABAJO,
	   b.PERSONAL_ACTIVO,
	   c.LUGAR_DE_TRABAJO
  FROM VBIO_MARCAJES_ORDEN_COLUMNAS AS a, PERSONAL AS b,
  UNIDADES_DE_TRABAJO AS c
  WHERE a.CODIGO_DE_MARCAJE   = b.CODIGO_MARCAJE_RELOJ
  AND c.CODIGO_UNIDAD_TRABAJO = b.CODIGO_UNIDAD_TRABAJO
  AND b.CODIGO_DE_PERSONAL    > 0
  AND b.CODIGO_DE_PERSONAL    < 8888
GO


