SELECT * FROM VNOM_MARCAS_IMPORTACION_RELOJ


SELECT * FROM NOMINAS_MARCAS_RELOJ

SELECT FECHA_DE_MARCAJE, CODIGO_DE_MARCAJE, HORA_DE_MARCAJE,
       ROW_NUMBER() OVER (PARTITION BY FECHA_DE_MARCAJE, CODIGO_DE_MARCAJE, HORA_DE_MARCAJE 
	                      ORDER BY FECHA_DE_MARCAJE, CODIGO_DE_MARCAJE, HORA_DE_MARCAJE) AS COLUMSEQUENCE
FROM NOMINAS_MARCAS_RELOJ;


SELECT HORA_DE_MARCAJE, FECHA_DE_MARCAJE, CODIGO_DE_MARCAJE,
       ROW_NUMBER() OVER (PARTITION BY CODIGO_DE_MARCAJE 
	                      ORDER BY CODIGO_DE_MARCAJE) AS COLUMSEQUENCE
FROM NOMINAS_MARCAS_RELOJ
--WHERE CODIGO_DE_MARCAJE = 29
--AND FECHA_DE_MARCAJE = '2019-08-05';



SELECT CODIGO_DE_MARCAJE, FECHA_DE_MARCAJE, MARCA1, MARCA2, MARCA3, MARCA4, MARCA5, MARCA6, MARCA7, MARCA8, MARCA9, MARCA10
FROM
(
SELECT FECHA_DE_MARCAJE, HORA_DE_MARCAJE, CODIGO_DE_MARCAJE, 
'MARCA' + CAST(ROW_NUMBER() OVER (PARTITION BY CODIGO_DE_MARCAJE, 
											   DAY(FECHA_DE_MARCAJE), 
											   MONTH(FECHA_DE_MARCAJE), 
											   YEAR(FECHA_DE_MARCAJE)  
								  ORDER BY FECHA_DE_MARCAJE,CODIGO_DE_MARCAJE) AS VARCHAR(10)) AS CANTIDAD_COLUMNAS
FROM DESCARGA_DE_MARCAJES
) TEMP
PIVOT
(
MAX(HORA_DE_MARCAJE)
FOR CANTIDAD_COLUMNAS IN (MARCA1, MARCA2, MARCA3, MARCA4, MARCA5, MARCA6, MARCA7, MARCA8, MARCA9, MARCA10)
) PIV


SELECT * FROM VNOM_MARCAS_IMPORTACION_RELOJ
WHERE CODIGO_DE_MARCAJE = '00029'
AND FECHA_DE_MARCAS = '20190805'
ORDER BY FECHA_DE_MARCAS, CODIGO_DE_MARCAJE


--SELECT * FROM NOMINAS_IMPORTACION_MARCAS_RELOJ

SELECT CODIGO_DE_MARCAJE_EMPLEADO, 
				   FECHA_DE_MARCAJE, 
				   HORA_DE_MARCAJE
			 FROM VNOM_MARCAS_IMPORTACION_RELOJ
			 WHERE CODIGO_DE_MARCAJE_EMPLEADO = 29
			 GROUP BY FECHA_DE_MARCAJE, CODIGO_DE_MARCAJE_EMPLEADO, HORA_DE_MARCAJE, 
					  MINUTOS, ULTIMO_MINUTO, SIGUIENTE_MINUTO
			ORDER BY FECHA_DE_MARCAJE, CODIGO_DE_MARCAJE_EMPLEADO, HORA_DE_MARCAJE;


SELECT CODIGO_DE_MARCAJE_EMPLEADO, 
				   FECHA_DE_MARCAJE, 
				   HORA_DE_MARCAJE, 
				   MINUTOS,
				   MINUTO_ACTUAL,
				   SIGUIENTE_MINUTO
			 FROM VNOM_MARCAS_IMPORTACION_RELOJ
			 WHERE CODIGO_DE_MARCAJE_EMPLEADO = 29
			 GROUP BY FECHA_DE_MARCAJE, CODIGO_DE_MARCAJE_EMPLEADO, HORA_DE_MARCAJE, 
					  MINUTOS, MINUTO_ACTUAL, SIGUIENTE_MINUTO
			ORDER BY FECHA_DE_MARCAJE, CODIGO_DE_MARCAJE_EMPLEADO, HORA_DE_MARCAJE;