SELECT * FROM VNOM_MARCAS_IMPORTACION_RELOJ

SELECT * FROM NOMINAS_MARCAS_RELOJ

DROP TABLE ESQUEMA_RH.COUNTRIES;
DROP SYNONYM COUNTRIES;

CREATE TABLE ESQUEMA_RH.COUNTRIES
   (COUNTRY VARCHAR(50),
    CITY VARCHAR(50));


CREATE SYNONYM dbo.COUNTRIES FOR ESQUEMA_RH.COUNTRIES;

SELECT * FROM COUNTRIES;

--DELETE FROM COUNTRIES;


INSERT INTO COUNTRIES VALUES ('USA', 'NY');
INSERT INTO COUNTRIES VALUES ('USA', 'HOUSTON');
INSERT INTO COUNTRIES VALUES ('USA', 'DALLAS');

INSERT INTO COUNTRIES VALUES ('INDIA', 'HYDERABAD');
INSERT INTO COUNTRIES VALUES ('INDIA', 'BANGALORE');
INSERT INTO COUNTRIES VALUES ('INDIA', 'NEW DELHI');

INSERT INTO COUNTRIES VALUES ('UK', 'LONDON');
INSERT INTO COUNTRIES VALUES ('UK', 'BIRMINGHAM');
INSERT INTO COUNTRIES VALUES ('UK', 'MANCHESTER');

SELECT * FROM COUNTRIES;

SELECT COUNTRY,CITY,
       ROW_NUMBER() OVER (PARTITION BY COUNTRY ORDER BY COUNTRY) AS COLUMSEQUENCE
FROM COUNTRIES;

SELECT COUNTRY, CITY1, CITY2, CITY3
FROM
(
SELECT COUNTRY,CITY,
'CITY' + CAST(ROW_NUMBER() OVER (PARTITION BY COUNTRY ORDER BY COUNTRY) AS VARCHAR(10)) AS COLUMSEQUENCE
FROM COUNTRIES
) TEMP
PIVOT
(
MAX(CITY)
FOR COLUMSEQUENCE IN (CITY1, CITY2, CITY3)
) PIV


INSERT INTO COUNTRIES VALUES ('INDIA', 'CHENNAI');

SELECT COUNTRY, CITY1, CITY2, CITY3, CITY4
FROM
(
SELECT COUNTRY,CITY,
'CITY' + CAST(ROW_NUMBER() OVER (PARTITION BY COUNTRY ORDER BY COUNTRY) AS VARCHAR(10)) AS COLUMSEQUENCE
FROM COUNTRIES
) TEMP
PIVOT
(
MAX(CITY)
FOR COLUMSEQUENCE IN (CITY1, CITY2, CITY3, CITY4)
) PIV


SELECT COUNTRY, CITY1, CITY2, CITY3, CITY4, CITY5
FROM
(
SELECT COUNTRY,CITY,
'CITY' + CAST(ROW_NUMBER() OVER (PARTITION BY COUNTRY ORDER BY COUNTRY) AS VARCHAR(10)) AS COLUMSEQUENCE
FROM COUNTRIES
) TEMP
PIVOT
(
MAX(CITY)
FOR COLUMSEQUENCE IN (CITY1, CITY2, CITY3, CITY4, CITY5)
) PIV


								